#!/usr/bin/env bash

set -euo pipefail

#%include help.sh

#%include autohelp.sh out.sh

#%include modules.sh

gits:main() {

    local action

    action="${1:-}"; shift || :

    [[ -n "$action" ]] || {
        gits:common:fetch-status
        exit
    }

    case "$action" in
    -mm)
        gits:commit "$action" "$@"
        ;;
    help)
        autohelp:print help
        ;;
    fs)
        gits:common:fetch-status
        ;;
    log)
        gits:log "$@"
        ;;
    profile)
        gits:profiles:_dispatch "$@"
        ;;
    push)
        gits:push "$@"
        ;;
    gc)
        gits:gc-full "$@"
        ;;
    *)
        gits:diff "$action" "$@"
        ;;
    esac
}

gits:main "$@"
