#!/usr/bin/env bash

#%include help.sh

#%include autohelp.sh out.sh

#%include modules.sh

gits:main() {

    local action

    action="${1:-}"; shift || :

    [[ -n "$action" ]] || {
        git status
        exit
    }

    case "$action" in
    -mm)
        gits:commit "$action" "$@"
        ;;
    help)
        autohelp:print help
        ;;
    fs)
        gits:common:fetch-status
        ;;
    log)
        gits:log "$@"
        ;;
    *)
        gits:diff "$action" "$@"
        ;;
    esac
}

gits:main "$@"
