#!/usr/bin/env bash


#%include autohelp.sh out.sh

#%include modules.sh

gits:helpcheck() {
    [[ -n "$*" ]] || {
        autohelp:print help
        exit 0
    }
}

gits:main() {
    gits:helpcheck "$@"

    local action

    action="$1"; shift

    case "$action" in
    fs)
        gits:common:fetch-status
        ;;
    *)
        gits:diff "$action" "$@"
        ;;
    esac
}

gits:main "$@"
